sh euclidtidy.sh bookIX/bookIX.html
sh euclidtidy.sh bookIX/propIX1.html
sh euclidtidy.sh bookIX/propIX10.html
sh euclidtidy.sh bookIX/propIX11.html
sh euclidtidy.sh bookIX/propIX12.html
sh euclidtidy.sh bookIX/propIX13.html
sh euclidtidy.sh bookIX/propIX14.html
sh euclidtidy.sh bookIX/propIX15.html
sh euclidtidy.sh bookIX/propIX16.html
sh euclidtidy.sh bookIX/propIX17.html
sh euclidtidy.sh bookIX/propIX18.html
sh euclidtidy.sh bookIX/propIX19.html
sh euclidtidy.sh bookIX/propIX2.html
sh euclidtidy.sh bookIX/propIX20.html
sh euclidtidy.sh bookIX/propIX21.html
sh euclidtidy.sh bookIX/propIX22.html
sh euclidtidy.sh bookIX/propIX23.html
sh euclidtidy.sh bookIX/propIX24.html
sh euclidtidy.sh bookIX/propIX25.html
sh euclidtidy.sh bookIX/propIX26.html
sh euclidtidy.sh bookIX/propIX27.html
sh euclidtidy.sh bookIX/propIX28.html
sh euclidtidy.sh bookIX/propIX29.html
sh euclidtidy.sh bookIX/propIX3.html
sh euclidtidy.sh bookIX/propIX30.html
sh euclidtidy.sh bookIX/propIX31.html
sh euclidtidy.sh bookIX/propIX32.html
sh euclidtidy.sh bookIX/propIX33.html
sh euclidtidy.sh bookIX/propIX34.html
sh euclidtidy.sh bookIX/propIX35.html
sh euclidtidy.sh bookIX/propIX36.html
sh euclidtidy.sh bookIX/propIX4.html
sh euclidtidy.sh bookIX/propIX5.html
sh euclidtidy.sh bookIX/propIX6.html
sh euclidtidy.sh bookIX/propIX7.html
sh euclidtidy.sh bookIX/propIX8.html
sh euclidtidy.sh bookIX/propIX9.html
