sh euclidtidy.sh bookIII/bookIII.html
sh euclidtidy.sh bookIII/defIII1.html
sh euclidtidy.sh bookIII/defIII10.html
sh euclidtidy.sh bookIII/defIII11.html
sh euclidtidy.sh bookIII/defIII2.html
sh euclidtidy.sh bookIII/defIII4.html
sh euclidtidy.sh bookIII/defIII6.html
sh euclidtidy.sh bookIII/propIII1.html
sh euclidtidy.sh bookIII/propIII10.html
sh euclidtidy.sh bookIII/propIII11.html
sh euclidtidy.sh bookIII/propIII12.html
sh euclidtidy.sh bookIII/propIII13.html
sh euclidtidy.sh bookIII/propIII14.html
sh euclidtidy.sh bookIII/propIII15.html
sh euclidtidy.sh bookIII/propIII16.html
sh euclidtidy.sh bookIII/propIII17.html
sh euclidtidy.sh bookIII/propIII18.html
sh euclidtidy.sh bookIII/propIII19.html
sh euclidtidy.sh bookIII/propIII2.html
sh euclidtidy.sh bookIII/propIII20.html
sh euclidtidy.sh bookIII/propIII21.html
sh euclidtidy.sh bookIII/propIII22.html
sh euclidtidy.sh bookIII/propIII23.html
sh euclidtidy.sh bookIII/propIII24.html
sh euclidtidy.sh bookIII/propIII25.html
sh euclidtidy.sh bookIII/propIII26.html
sh euclidtidy.sh bookIII/propIII27.html
sh euclidtidy.sh bookIII/propIII28.html
sh euclidtidy.sh bookIII/propIII29.html
sh euclidtidy.sh bookIII/propIII3.html
sh euclidtidy.sh bookIII/propIII30.html
sh euclidtidy.sh bookIII/propIII31.html
sh euclidtidy.sh bookIII/propIII32.html
sh euclidtidy.sh bookIII/propIII33.html
sh euclidtidy.sh bookIII/propIII34.html
sh euclidtidy.sh bookIII/propIII35.html
sh euclidtidy.sh bookIII/propIII36.html
sh euclidtidy.sh bookIII/propIII37.html
sh euclidtidy.sh bookIII/propIII4.html
sh euclidtidy.sh bookIII/propIII5.html
sh euclidtidy.sh bookIII/propIII6.html
sh euclidtidy.sh bookIII/propIII7.html
sh euclidtidy.sh bookIII/propIII8.html
sh euclidtidy.sh bookIII/propIII9.html
