sh euclidtidy.sh bookXII/bookXII.html
sh euclidtidy.sh bookXII/propXII1.html
sh euclidtidy.sh bookXII/propXII10.html
sh euclidtidy.sh bookXII/propXII11.html
sh euclidtidy.sh bookXII/propXII12.html
sh euclidtidy.sh bookXII/propXII13.html
sh euclidtidy.sh bookXII/propXII14.html
sh euclidtidy.sh bookXII/propXII15.html
sh euclidtidy.sh bookXII/propXII16.html
sh euclidtidy.sh bookXII/propXII17.html
sh euclidtidy.sh bookXII/propXII18.html
sh euclidtidy.sh bookXII/propXII2.html
sh euclidtidy.sh bookXII/propXII3.html
sh euclidtidy.sh bookXII/propXII4.html
sh euclidtidy.sh bookXII/propXII5.html
sh euclidtidy.sh bookXII/propXII6.html
sh euclidtidy.sh bookXII/propXII7.html
sh euclidtidy.sh bookXII/propXII8.html
sh euclidtidy.sh bookXII/propXII9.html
