sh euclidtidy.sh bookVIII/bookVIII.html
sh euclidtidy.sh bookVIII/propVIII1.html
sh euclidtidy.sh bookVIII/propVIII10.html
sh euclidtidy.sh bookVIII/propVIII11.html
sh euclidtidy.sh bookVIII/propVIII12.html
sh euclidtidy.sh bookVIII/propVIII13.html
sh euclidtidy.sh bookVIII/propVIII14.html
sh euclidtidy.sh bookVIII/propVIII15.html
sh euclidtidy.sh bookVIII/propVIII16.html
sh euclidtidy.sh bookVIII/propVIII17.html
sh euclidtidy.sh bookVIII/propVIII18.html
sh euclidtidy.sh bookVIII/propVIII19.html
sh euclidtidy.sh bookVIII/propVIII2.html
sh euclidtidy.sh bookVIII/propVIII20.html
sh euclidtidy.sh bookVIII/propVIII21.html
sh euclidtidy.sh bookVIII/propVIII22.html
sh euclidtidy.sh bookVIII/propVIII23.html
sh euclidtidy.sh bookVIII/propVIII24.html
sh euclidtidy.sh bookVIII/propVIII25.html
sh euclidtidy.sh bookVIII/propVIII26.html
sh euclidtidy.sh bookVIII/propVIII27.html
sh euclidtidy.sh bookVIII/propVIII3.html
sh euclidtidy.sh bookVIII/propVIII4.html
sh euclidtidy.sh bookVIII/propVIII5.html
sh euclidtidy.sh bookVIII/propVIII6.html
sh euclidtidy.sh bookVIII/propVIII7.html
sh euclidtidy.sh bookVIII/propVIII8.html
sh euclidtidy.sh bookVIII/propVIII9.html
