sh euclidtidy.sh bookVII/bookVII.html
sh euclidtidy.sh bookVII/defVII1.html
sh euclidtidy.sh bookVII/defVII11.html
sh euclidtidy.sh bookVII/defVII15.html
sh euclidtidy.sh bookVII/defVII20.html
sh euclidtidy.sh bookVII/defVII21.html
sh euclidtidy.sh bookVII/defVII22.html
sh euclidtidy.sh bookVII/defVII3.html
sh euclidtidy.sh bookVII/defVII6.html
sh euclidtidy.sh bookVII/propVII1.html
sh euclidtidy.sh bookVII/propVII10.html
sh euclidtidy.sh bookVII/propVII11.html
sh euclidtidy.sh bookVII/propVII12.html
sh euclidtidy.sh bookVII/propVII13.html
sh euclidtidy.sh bookVII/propVII14.html
sh euclidtidy.sh bookVII/propVII15.html
sh euclidtidy.sh bookVII/propVII16.html
sh euclidtidy.sh bookVII/propVII17.html
sh euclidtidy.sh bookVII/propVII18.html
sh euclidtidy.sh bookVII/propVII19.html
sh euclidtidy.sh bookVII/propVII2.html
sh euclidtidy.sh bookVII/propVII20.html
sh euclidtidy.sh bookVII/propVII21.html
sh euclidtidy.sh bookVII/propVII22.html
sh euclidtidy.sh bookVII/propVII23.html
sh euclidtidy.sh bookVII/propVII24.html
sh euclidtidy.sh bookVII/propVII25.html
sh euclidtidy.sh bookVII/propVII26.html
sh euclidtidy.sh bookVII/propVII27.html
sh euclidtidy.sh bookVII/propVII28.html
sh euclidtidy.sh bookVII/propVII29.html
sh euclidtidy.sh bookVII/propVII3.html
sh euclidtidy.sh bookVII/propVII30.html
sh euclidtidy.sh bookVII/propVII31.html
sh euclidtidy.sh bookVII/propVII32.html
sh euclidtidy.sh bookVII/propVII33.html
sh euclidtidy.sh bookVII/propVII34.html
sh euclidtidy.sh bookVII/propVII35.html
sh euclidtidy.sh bookVII/propVII36.html
sh euclidtidy.sh bookVII/propVII37.html
sh euclidtidy.sh bookVII/propVII38.html
sh euclidtidy.sh bookVII/propVII39.html
sh euclidtidy.sh bookVII/propVII4.html
sh euclidtidy.sh bookVII/propVII5.html
sh euclidtidy.sh bookVII/propVII6.html
sh euclidtidy.sh bookVII/propVII7.html
sh euclidtidy.sh bookVII/propVII8.html
sh euclidtidy.sh bookVII/propVII9.html
