sh euclidtidy.sh bookVI/bookVI.html
sh euclidtidy.sh bookVI/defVI1.html
sh euclidtidy.sh bookVI/defVI2.html
sh euclidtidy.sh bookVI/defVI3.html
sh euclidtidy.sh bookVI/defVI4.html
sh euclidtidy.sh bookVI/propVI1.html
sh euclidtidy.sh bookVI/propVI10.html
sh euclidtidy.sh bookVI/propVI11.html
sh euclidtidy.sh bookVI/propVI12.html
sh euclidtidy.sh bookVI/propVI13.html
sh euclidtidy.sh bookVI/propVI14.html
sh euclidtidy.sh bookVI/propVI15.html
sh euclidtidy.sh bookVI/propVI16.html
sh euclidtidy.sh bookVI/propVI17.html
sh euclidtidy.sh bookVI/propVI18.html
sh euclidtidy.sh bookVI/propVI19.html
sh euclidtidy.sh bookVI/propVI2.html
sh euclidtidy.sh bookVI/propVI20.html
sh euclidtidy.sh bookVI/propVI21.html
sh euclidtidy.sh bookVI/propVI22.html
sh euclidtidy.sh bookVI/propVI23.html
sh euclidtidy.sh bookVI/propVI24.html
sh euclidtidy.sh bookVI/propVI25.html
sh euclidtidy.sh bookVI/propVI26.html
sh euclidtidy.sh bookVI/propVI27.html
sh euclidtidy.sh bookVI/propVI28.html
sh euclidtidy.sh bookVI/propVI29.html
sh euclidtidy.sh bookVI/propVI3.html
sh euclidtidy.sh bookVI/propVI30.html
sh euclidtidy.sh bookVI/propVI31.html
sh euclidtidy.sh bookVI/propVI32.html
sh euclidtidy.sh bookVI/propVI33.html
sh euclidtidy.sh bookVI/propVI4.html
sh euclidtidy.sh bookVI/propVI5.html
sh euclidtidy.sh bookVI/propVI6.html
sh euclidtidy.sh bookVI/propVI7.html
sh euclidtidy.sh bookVI/propVI8.html
sh euclidtidy.sh bookVI/propVI9.html
