sh euclidtidy.sh bookX/bookX.html
sh euclidtidy.sh bookX/defX.I.html
sh euclidtidy.sh bookX/defX.I.html
sh euclidtidy.sh bookX/propX1.html
sh euclidtidy.sh bookX/propX10.html
sh euclidtidy.sh bookX/propX100.html
sh euclidtidy.sh bookX/propX101.html
sh euclidtidy.sh bookX/propX102.html
sh euclidtidy.sh bookX/propX103.html
sh euclidtidy.sh bookX/propX104.html
sh euclidtidy.sh bookX/propX105.html
sh euclidtidy.sh bookX/propX106.html
sh euclidtidy.sh bookX/propX107.html
sh euclidtidy.sh bookX/propX108.html
sh euclidtidy.sh bookX/propX109.html
sh euclidtidy.sh bookX/propX11.html
sh euclidtidy.sh bookX/propX110.html
sh euclidtidy.sh bookX/propX111.html
sh euclidtidy.sh bookX/propX112.html
sh euclidtidy.sh bookX/propX113.html
sh euclidtidy.sh bookX/propX114.html
sh euclidtidy.sh bookX/propX115.html
sh euclidtidy.sh bookX/propX12.html
sh euclidtidy.sh bookX/propX13.html
sh euclidtidy.sh bookX/propX14.html
sh euclidtidy.sh bookX/propX15.html
sh euclidtidy.sh bookX/propX16.html
sh euclidtidy.sh bookX/propX17.html
sh euclidtidy.sh bookX/propX18.html
sh euclidtidy.sh bookX/propX19.html
sh euclidtidy.sh bookX/propX2.html
sh euclidtidy.sh bookX/propX20.html
sh euclidtidy.sh bookX/propX21.html
sh euclidtidy.sh bookX/propX22.html
sh euclidtidy.sh bookX/propX23.html
sh euclidtidy.sh bookX/propX24.html
sh euclidtidy.sh bookX/propX25.html
sh euclidtidy.sh bookX/propX26.html
sh euclidtidy.sh bookX/propX27.html
sh euclidtidy.sh bookX/propX28.html
sh euclidtidy.sh bookX/propX29.html
sh euclidtidy.sh bookX/propX3.html
sh euclidtidy.sh bookX/propX30.html
sh euclidtidy.sh bookX/propX31.html
sh euclidtidy.sh bookX/propX32.html
sh euclidtidy.sh bookX/propX33.html
sh euclidtidy.sh bookX/propX34.html
sh euclidtidy.sh bookX/propX35.html
sh euclidtidy.sh bookX/propX36.html
sh euclidtidy.sh bookX/propX37.html
sh euclidtidy.sh bookX/propX38.html
sh euclidtidy.sh bookX/propX39.html
sh euclidtidy.sh bookX/propX4.html
sh euclidtidy.sh bookX/propX40.html
sh euclidtidy.sh bookX/propX41.html
sh euclidtidy.sh bookX/propX42.html
sh euclidtidy.sh bookX/propX43.html
sh euclidtidy.sh bookX/propX44.html
sh euclidtidy.sh bookX/propX45.html
sh euclidtidy.sh bookX/propX46.html
sh euclidtidy.sh bookX/propX47.html
sh euclidtidy.sh bookX/propX48.html
sh euclidtidy.sh bookX/propX49.html
sh euclidtidy.sh bookX/propX5.html
sh euclidtidy.sh bookX/propX50.html
sh euclidtidy.sh bookX/propX51.html
sh euclidtidy.sh bookX/propX52.html
sh euclidtidy.sh bookX/propX53.html
sh euclidtidy.sh bookX/propX54.html
sh euclidtidy.sh bookX/propX55.html
sh euclidtidy.sh bookX/propX56.html
sh euclidtidy.sh bookX/propX57.html
sh euclidtidy.sh bookX/propX58.html
sh euclidtidy.sh bookX/propX59.html
sh euclidtidy.sh bookX/propX6.html
sh euclidtidy.sh bookX/propX60.html
sh euclidtidy.sh bookX/propX61.html
sh euclidtidy.sh bookX/propX62.html
sh euclidtidy.sh bookX/propX63.html
sh euclidtidy.sh bookX/propX64.html
sh euclidtidy.sh bookX/propX65.html
sh euclidtidy.sh bookX/propX66.html
sh euclidtidy.sh bookX/propX67.html
sh euclidtidy.sh bookX/propX68.html
sh euclidtidy.sh bookX/propX69.html
sh euclidtidy.sh bookX/propX7.html
sh euclidtidy.sh bookX/propX70.html
sh euclidtidy.sh bookX/propX71.html
sh euclidtidy.sh bookX/propX72.html
sh euclidtidy.sh bookX/propX73.html
sh euclidtidy.sh bookX/propX74.html
sh euclidtidy.sh bookX/propX75.html
sh euclidtidy.sh bookX/propX76.html
sh euclidtidy.sh bookX/propX77.html
sh euclidtidy.sh bookX/propX78.html
sh euclidtidy.sh bookX/propX79.html
sh euclidtidy.sh bookX/propX8.html
sh euclidtidy.sh bookX/propX80.html
sh euclidtidy.sh bookX/propX81.html
sh euclidtidy.sh bookX/propX82.html
sh euclidtidy.sh bookX/propX83.html
sh euclidtidy.sh bookX/propX84.html
sh euclidtidy.sh bookX/propX85.html
sh euclidtidy.sh bookX/propX86.html
sh euclidtidy.sh bookX/propX87.html
sh euclidtidy.sh bookX/propX88.html
sh euclidtidy.sh bookX/propX89.html
sh euclidtidy.sh bookX/propX9.html
sh euclidtidy.sh bookX/propX90.html
sh euclidtidy.sh bookX/propX91.html
sh euclidtidy.sh bookX/propX92.html
sh euclidtidy.sh bookX/propX93.html
sh euclidtidy.sh bookX/propX94.html
sh euclidtidy.sh bookX/propX95.html
sh euclidtidy.sh bookX/propX96.html
sh euclidtidy.sh bookX/propX97.html
sh euclidtidy.sh bookX/propX98.html
sh euclidtidy.sh bookX/propX99.html
