sh euclidtidy.sh bookIV/bookIV.html
sh euclidtidy.sh bookIV/defIV.html
sh euclidtidy.sh bookIV/propIV1.html
sh euclidtidy.sh bookIV/propIV10.html
sh euclidtidy.sh bookIV/propIV11.html
sh euclidtidy.sh bookIV/propIV12.html
sh euclidtidy.sh bookIV/propIV13.html
sh euclidtidy.sh bookIV/propIV14.html
sh euclidtidy.sh bookIV/propIV15.html
sh euclidtidy.sh bookIV/propIV16.html
sh euclidtidy.sh bookIV/propIV2.html
sh euclidtidy.sh bookIV/propIV3.html
sh euclidtidy.sh bookIV/propIV4.html
sh euclidtidy.sh bookIV/propIV5.html
sh euclidtidy.sh bookIV/propIV6.html
sh euclidtidy.sh bookIV/propIV7.html
sh euclidtidy.sh bookIV/propIV8.html
sh euclidtidy.sh bookIV/propIV9.html
