sh euclidtidy.sh bookV/bookV.html
sh euclidtidy.sh bookV/defV1.html
sh euclidtidy.sh bookV/defV11.html
sh euclidtidy.sh bookV/defV14.html
sh euclidtidy.sh bookV/defV17.html
sh euclidtidy.sh bookV/defV3.html
sh euclidtidy.sh bookV/defV4.html
sh euclidtidy.sh bookV/defV5.html
sh euclidtidy.sh bookV/defV7.html
sh euclidtidy.sh bookV/defV8.html
sh euclidtidy.sh bookV/propV1.html
sh euclidtidy.sh bookV/propV10.html
sh euclidtidy.sh bookV/propV11.html
sh euclidtidy.sh bookV/propV12.html
sh euclidtidy.sh bookV/propV13.html
sh euclidtidy.sh bookV/propV14.html
sh euclidtidy.sh bookV/propV15.html
sh euclidtidy.sh bookV/propV16.html
sh euclidtidy.sh bookV/propV17.html
sh euclidtidy.sh bookV/propV18.html
sh euclidtidy.sh bookV/propV19.html
sh euclidtidy.sh bookV/propV2.html
sh euclidtidy.sh bookV/propV20.html
sh euclidtidy.sh bookV/propV21.html
sh euclidtidy.sh bookV/propV22.html
sh euclidtidy.sh bookV/propV23.html
sh euclidtidy.sh bookV/propV24.html
sh euclidtidy.sh bookV/propV25.html
sh euclidtidy.sh bookV/propV3.html
sh euclidtidy.sh bookV/propV4.html
sh euclidtidy.sh bookV/propV5.html
sh euclidtidy.sh bookV/propV6.html
sh euclidtidy.sh bookV/propV7.html
sh euclidtidy.sh bookV/propV8.html
sh euclidtidy.sh bookV/propV9.html
