sh euclidtidy.sh bookXI/bookXI.html
sh euclidtidy.sh bookXI/defXI1.html
sh euclidtidy.sh bookXI/defXI11.html
sh euclidtidy.sh bookXI/defXI12.html
sh euclidtidy.sh bookXI/defXI14.html
sh euclidtidy.sh bookXI/defXI18.html
sh euclidtidy.sh bookXI/defXI21.html
sh euclidtidy.sh bookXI/defXI24.html
sh euclidtidy.sh bookXI/defXI25.html
sh euclidtidy.sh bookXI/defXI3.html
sh euclidtidy.sh bookXI/defXI6.html
sh euclidtidy.sh bookXI/defXI9.html
sh euclidtidy.sh bookXI/propXI1.html
sh euclidtidy.sh bookXI/propXI10.html
sh euclidtidy.sh bookXI/propXI11.html
sh euclidtidy.sh bookXI/propXI12.html
sh euclidtidy.sh bookXI/propXI13.html
sh euclidtidy.sh bookXI/propXI14.html
sh euclidtidy.sh bookXI/propXI15.html
sh euclidtidy.sh bookXI/propXI16.html
sh euclidtidy.sh bookXI/propXI17.html
sh euclidtidy.sh bookXI/propXI18.html
sh euclidtidy.sh bookXI/propXI19.html
sh euclidtidy.sh bookXI/propXI2.html
sh euclidtidy.sh bookXI/propXI20.html
sh euclidtidy.sh bookXI/propXI21.html
sh euclidtidy.sh bookXI/propXI22.html
sh euclidtidy.sh bookXI/propXI23.html
sh euclidtidy.sh bookXI/propXI24.html
sh euclidtidy.sh bookXI/propXI25.html
sh euclidtidy.sh bookXI/propXI26.html
sh euclidtidy.sh bookXI/propXI27.html
sh euclidtidy.sh bookXI/propXI28.html
sh euclidtidy.sh bookXI/propXI29.html
sh euclidtidy.sh bookXI/propXI3.html
sh euclidtidy.sh bookXI/propXI30.html
sh euclidtidy.sh bookXI/propXI31.html
sh euclidtidy.sh bookXI/propXI32.html
sh euclidtidy.sh bookXI/propXI33.html
sh euclidtidy.sh bookXI/propXI34.html
sh euclidtidy.sh bookXI/propXI35.html
sh euclidtidy.sh bookXI/propXI36.html
sh euclidtidy.sh bookXI/propXI37.html
sh euclidtidy.sh bookXI/propXI38.html
sh euclidtidy.sh bookXI/propXI39.html
sh euclidtidy.sh bookXI/propXI4.html
sh euclidtidy.sh bookXI/propXI5.html
sh euclidtidy.sh bookXI/propXI6.html
sh euclidtidy.sh bookXI/propXI7.html
sh euclidtidy.sh bookXI/propXI8.html
sh euclidtidy.sh bookXI/propXI9.html
