sh euclidtidy.sh bookXIII/bookXIII.html
sh euclidtidy.sh bookXIII/propXIII1.html
sh euclidtidy.sh bookXIII/propXIII10.html
sh euclidtidy.sh bookXIII/propXIII11.html
sh euclidtidy.sh bookXIII/propXIII12.html
sh euclidtidy.sh bookXIII/propXIII13.html
sh euclidtidy.sh bookXIII/propXIII14.html
sh euclidtidy.sh bookXIII/propXIII15.html
sh euclidtidy.sh bookXIII/propXIII16.html
sh euclidtidy.sh bookXIII/propXIII17.html
sh euclidtidy.sh bookXIII/propXIII18.html
sh euclidtidy.sh bookXIII/propXIII2.html
sh euclidtidy.sh bookXIII/propXIII3.html
sh euclidtidy.sh bookXIII/propXIII4.html
sh euclidtidy.sh bookXIII/propXIII5.html
sh euclidtidy.sh bookXIII/propXIII6.html
sh euclidtidy.sh bookXIII/propXIII7.html
sh euclidtidy.sh bookXIII/propXIII8.html
sh euclidtidy.sh bookXIII/propXIII9.html
